// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umvaywtxpxpyybpkwptc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtdmF5d3R4cHhweXlicGt3cHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MzM1MDQsImV4cCI6MjA1NzMwOTUwNH0.UyOWu-kBwNIL9m0VjlDFVFEubZsNHKtapmnNaK_VwwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);