[features]
seeds = false
skip-lint = false

[programs.testnet]
pay_to_reply = "GPS2swU3p4XGWisAh3n4QWQuMvrQdfnz2eSwME2dp66A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.sonic.game"
wallet = "~/.config/solana/id.json"

[toolchain]
anchor_version = "0.26.0"
solana_version = "2.1.16"

# After deployment, use solana config to set URL back to Sonic:
# solana config set --url https://api.testnet.sonic.game 